### ISSUE TITLE
Problem when loading reference data ?

### ISSUE THREAD

**Issue by cabanesc** [euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool#14]
Hi Ed,

update_salinity_mapping.py crashed at profile 1 when I ran it for float 3901960 (ref ARGO2019v03), with the following error:

UPDATE_SALINITY_MAPPING: Working on profile  0
time elapsed:  5.4  seconds
UPDATE_SALINITY_MAPPING: Working on profile  1
Traceback (most recent call last):
  File "/home1/homedir5/perso/ccabanes/dvlpRD/Argo/argodmqc_owc/ow_calibration/get_region/get_region_data.py", line 173, in get_region_data
    grid_long = wrap_longitude(grid_long)
  File "/home1/homedir5/perso/ccabanes/dvlpRD/Argo/argodmqc_owc/ow_calibration/get_region/data_functions/wrap_longitude.py", line 27, in wrap_longitude
    neg_long = np.argwhere(grid_long < 0)
TypeError: '<' not supported between instances of 'list' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "owc_calibration.py", line 73, in <module>
    update_salinity_mapping("/", FLOAT_NAME, USER_CONFIG)
  File "/home1/homedir5/perso/ccabanes/dvlpRD/Argo/argodmqc_owc/ow_calibration/update_salinity_mapping/update_salinity_mapping.py", line 334, in update_salinity_mapping
    float_pres)
  File "/home1/homedir5/perso/ccabanes/dvlpRD/Argo/argodmqc_owc/ow_calibration/get_region/get_region_data.py", line 199, in get_region_data
    raise Exception("NO DATA FOUND")
Exception: NO DATA FOUND

----
*[wmo_boxes_argo.mat.gz](https://github.com/euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool/files/4744315/wmo_boxes_argo.mat.gz)

*Reference database : ARGO2019v03
* source file: 3901960.mat (example provided with the software)
*Configuration file: 

'CONFIG_DIRECTORY': "data/constants/",
        'CONFIG_COASTLINES': "coastdat.mat",
        'CONFIG_WMO_BOXES': "wmo_boxes_argo.mat",
        'CONFIG_SAF': "TypicalProfileAroundSAF.mat",

        # ===============================
        #
        #    Objective Mapping Parameters
        #

        # max number of historical casts used in objective mapping
        'CONFIG_MAX_CASTS': 300,

        # 1=use PV constraint, 0=don't use PV constraint, in objective mapping
        'MAP_USE_PV': 0,

        # 1=use SAF separation criteria, 0=don't use SAF separation criteria, in objective mapping
        'MAP_USE_SAF': 0,

        # spatial decorrelation scales, in degrees
        'MAPSCALE_LONGITUDE_LARGE': 8,
        'MAPSCALE_LONGITUDE_SMALL': 4,
        'MAPSCALE_LATITUDE_LARGE': 4,
        'MAPSCALE_LATITUDE_SMALL': 2,

        # cross-isobath scales, dimensionless, see BS(2005)
        'MAPSCALE_PHI_LARGE': 0.5,
        'MAPSCALE_PHI_SMALL': 0.1,

        # temporal decorrelation scale, in years
        'MAPSCALE_AGE_LARGE': 20,
        'MAPSCALE_AGE_SMALL': 10,

        # exclude the top xxx dbar of the water column
        'MAP_P_EXCLUDE': 200,

        # only use historical data that are within +/- yyy dbar from float data
        'MAP_P_DELTA': 250
    }

**Comment by kamwal** [comment]
I think that I have found the same issue with  reading Argo reference data (ARGO_for_DMQC_2020V01.mat) and logged it to [https://github.com/euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool/issues/8](url)

**Comment by edsmall-bodc** [comment]
Looks to be the same as [this issue](https://github.com/euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool/issues/13)

@cabanesc can you confirm it is the same bug? We can then close this issue as a duplicate issue

**Comment by cabanesc** [comment]
Yes it's the same bug, we can close the issue.
