### ISSUE TITLE
Update_salinity_mapping_test.py failed:  problem in selecting reference data?

### ISSUE THREAD

**Issue by cabanesc** [euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool#15]
Hi Ed,

When I run update_salinity_mapping_test.py, it fails for almost all the floats I tested.
 I hope I am not doing anything wrong, but it might be worth checking on your side.
Here is an example of a float that failed the test:
float : 6902766 
[6902766.mat.gz](https://github.com/euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool/files/4750657/6902766.mat.gz)

configuration_file:
[load_configuration.py.gz](https://github.com/euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool/files/4751044/load_configuration.py.gz)

Reference database: CTD2019V01

Before running update_salinity_mapping_test.py, I plotted the location of select_hist in the map_6902766.mat files from matlab and python runs. It seems that the selection of reference data is not the same in the two runs. Python seems to select data in the full wmo boxes while matlab selects within the ellipse:
![slect_hist](https://user-images.githubusercontent.com/38859979/84129592-75415200-aa42-11ea-8f09-130ae26dfc5f.PNG)

Here is the output of update_salinity_mapping_test.py:

/home1/homedir5/perso/ccabanes/dvlpRD/Argo/argodmqc_owc/ow_calibration/update_salinity_mapping/update_salinity_mapping.py:488: RuntimeWarning: invalid value encountered in less
  bad_sal_30 = np.argwhere(la_mapped_sal < 30)
/home1/homedir5/perso/ccabanes/dvlpRD/Argo/argodmqc_owc/ow_calibration/update_salinity_mapping/update_salinity_mapping.py:489: RuntimeWarning: invalid value encountered in greater
  bad_sal_40 = np.argwhere(la_mapped_sal > 40)
.Testing update_salinity_mapping gives correct signal salinity
F

==========================================================

FAIL: test_mapped_sal_output (ow_calibration.update_salinity_mapping.update_salinity_mapping_test.MyTestCase)

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home1/homedir5/perso/ccabanes/dvlpRD/Argo/argodmqc_owc/ow_calibration/update_salinity_mapping/update_salinity_mapping_test.py", line 97, in test_mapped_sal_output
    "error: mean of mapped salinities "
AssertionError: 35.27936812165678 != 35.30877090762167 within 3 places (0.029402785964890654 difference) : error: mean of mapped salinities differ between python andd matlab

============================================================

FAIL: test_mapped_salerrors_output (ow_calibration.update_salinity_mapping.update_salinity_mapping_test.MyTestCase)

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home1/homedir5/perso/ccabanes/dvlpRD/Argo/argodmqc_owc/ow_calibration/update_salinity_mapping/update_salinity_mapping_test.py", line 114, in test_mapped_salerrors_output
    "error: mean of salinity errors "
AssertionError: 0.06607353038637838 != 0.04630332284511441 within 3 places (0.01977020754126397 difference) : error: mean of salinity errors differ between python andd matlab

=========================================================

FAIL: test_noise_sal_output (ow_calibration.update_salinity_mapping.update_salinity_mapping_test.MyTestCase)

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home1/homedir5/perso/ccabanes/dvlpRD/Argo/argodmqc_owc/ow_calibration/update_salinity_mapping/update_salinity_mapping_test.py", line 131, in test_noise_sal_output
    "error: mean of noise salinity "
AssertionError: 0.0010533217049915934 != 0.0005326280647667427 within 3 places (0.0005206936402248507 difference) : error: mean of noise salinity differ between python andd matlab

===========================================================

FAIL: test_signal_sal_output (ow_calibration.update_salinity_mapping.update_salinity_mapping_test.MyTestCase)

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home1/homedir5/perso/ccabanes/dvlpRD/Argo/argodmqc_owc/ow_calibration/update_salinity_mapping/update_salinity_mapping_test.py", line 148, in test_signal_sal_output
    "error: mean of signal salinity "
AssertionError: 0.005452179775194339 != 0.0028584300392123533 within 3 places (0.0025937497359819857 difference) : error: mean of signal salinity differ between python andd matlab

----------------------------------------------------------------------
Ran 6 tests in 8091.000s

FAILED (failures=4)

**Comment by edsmall-bodc** [comment]
This does appear that the python version is selecting too much data, and yes, outside of the area highlighted by your criteria. It doesn't look like you are doing anything wrong (unless the parameters in your set up file are different from each other?).

I will investigate.

**Comment by edsmall-bodc** [comment]
Just to add, it makes sense that this would cause the mapped values validation tests to fail, as the cluster to the northwest of the float profiles would probably cause significant change here.

**Comment by edsmall-bodc** [comment]
And yes, the "squareness" of the data selected from the python version is suspicious - it does seem to simply be selecting all the data in the wmo box, and not filtering any out. I will investigate this next week, and I will likely make this task my top priority for during the start of my next sprint.

**Comment by kamwal** [comment]
I am sending some other examples of data selection:

(1) Here was the same issue with "squareness" of selected data by Python:

[3900560.zip](https://github.com/euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool/files/4918669/3900560.zip)

Left- Python data; Right- Matlab data

![image](https://user-images.githubusercontent.com/57108044/87423501-53ebfc80-c5d2-11ea-8777-11fe73d017fb.png)

The same float, but with a smaller spatial scale
[smaller_scale.zip](https://github.com/euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool/files/4923918/smaller_scale.zip)

![image](https://user-images.githubusercontent.com/57108044/87522358-6d964e00-c67d-11ea-93c1-5b80f7218dd0.png)

(2) The output from Python and matlab are quite similar, however ther eis some inconsistency in selected data to the south from the float:
[2901102.zip](https://github.com/euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool/files/4918749/2901102.zip)

Left- Python data; Right- Matlab data

![image](https://user-images.githubusercontent.com/57108044/87424833-96aed400-c5d4-11ea-81c9-c00d66cad408.png)

**Comment by edsmall-bodc** [comment]
The above don't seem to have remotely the same issue, and could easily be a result of the fact that a third of the data is selected randomly (provided it meets the correlation requirements).

The original example provided by @cabanesc has a HUGE amount more data (and the data seems to be taking a curious square like shape).

Hmm! Will continue to investigate!

**Comment by kamwal** [comment]
This example should be more convincing of some strange "squareness" of selected data:

[3901985.zip](https://github.com/euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool/files/4918993/3901985.zip)
 

Left- Python data; Right- Matlab data
![image](https://user-images.githubusercontent.com/57108044/87429289-76cede80-c5db-11ea-90b8-2a3f54293075.png)

**Comment by edsmall-bodc** [comment]
I suspect that the problem isn't the ellipse at all, but that we are not loading in other WMO boxes, so the random selection has no choice but to confine itself to a single box.

**Comment by matdon17** [comment]
@edsmall-bodc whilst that might be true, I'm not sure that would explain the original issue form @cabanesc as her Matlab data selection is entirely within the Python data selection.

In some of the other cases, different data is being selected beyond the initially apparent squareness - in the last example from @kamwal there is data selected all the way in the east coast of the USA, despite the squareness at 10oN.

It might be worth checking whether, for example, spatial scales have been swapped or something similar.

**Comment by cabanesc** [comment]
Hi Ed,
 I don't know if you could progress on this problem but comparing
find_best_hist.py and find_best_hist.m I wonder if the problem would not
come from the following :
In the matlab program, we start building index_ellipse, the indexes of all
the points in (grid_long, grid_lat) that are inside the ellipse.We then
build the arrays hist_long and hist_lat which contain only the points
inside the ellipse. length(hist_long) <= length(grid_lon)
Then, if there are more points than max_casts within the ellipse, we
randomly take 1/3 of the max_casts points in (hist_long, hist_lat). The
random_index is thus relative to (hist_long, hist_lat).
To have an index relative to (grid_long, grid_lat), i.e. the initial list
of stations, we finally construct i1=index_ellipse( index_random ) ;
I'm not sure if this last step is in the python program. It might be worth
checking. This would explain why the python selection is outside the
ellipse and follows the square shape of the wmo boxes.

Cecile

**Comment by edsmall-bodc** [comment]
@cabanesc Thank you for that insight, it's made me have a close look in the right place. I think you might be 90% of the way there.. The problem might also be that I need to make index_ellipse be a deep copy of index - will look at it today and let you know!

**Comment by kamwal** [comment]
This issue has been fixed and merge to master branch:
[fix branch](https://github.com/euroargodev/argodmqc_owc/pull/49)
