### ISSUE TITLE
Bug with CONFIG_MAX_CAST data selection ?

### ISSUE THREAD

**Issue by kamwal** [euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool#16]
I have found error associated with update salinity mapping. Debuger is pointing to the number of CONFIG_MAX_CAST. 
I am including the obtained error below:

`UPDATE_SALINITY_MAPPING: Working on profile  33
Traceback (most recent call last):
  File "L:/users/argo/kamwal/OWC_Python_Test_1/owc-software-python/owc_calibration.py", line 73, in <module>
    update_salinity_mapping("/", FLOAT_NAME, USER_CONFIG)
  File "L:\users\argo\kamwal\OWC_Python_Test_1\owc-software-python\ow_calibration\update_salinity_mapping\update_salinity_mapping.py", line 301, in update_salinity_mapping
    grid_elev, grid_x, grid_y = get_topo_grid(np.amin(grid_long_tbase) - 1,
  File "L:\users\argo\kamwal\OWC_Python_Test_1\owc-software-python\ow_calibration\tbase_decoder\tbase_decoder.py", line 70, in get_topo_grid
    elev_file.seek((i + decoder[3]) * 360 * 12 * 2 + decoder[0] * 2)
OSError: [Errno 22] Invalid argument
`

WMO: 6901178
Reference data: CTD_for_DMQC_2019v01.m
WMO boxes: wmo_boxes_ctd.mat
Objective mapping parameters:

`% Objective Mapping Parameters
%
% max number of historical casts used in objective mapping
CONFIG_MAX_CASTS=300
% 1=use PV constraint, 0=don't use PV constraint, in objective mapping
MAP_USE_PV=0
% 1=use SAF separation criteria, 0=don't use SAF separation criteria, in objective mapping
MAP_USE_SAF=0

% spatial decorrelation scales, in degrees
MAPSCALE_LONGITUDE_LARGE=8
MAPSCALE_LONGITUDE_SMALL=4
MAPSCALE_LATITUDE_LARGE=4
MAPSCALE_LATITUDE_SMALL=2
% cross-isobath scales, dimensionless, see BS(2005)
MAPSCALE_PHI_LARGE=0.1
MAPSCALE_PHI_SMALL=0.02
% temporal decorrelation scale, in years
MAPSCALE_AGE=5
MAPSCALE_AGE_LARGE=20
% exclude the top xxx dbar of the water column
MAP_P_EXCLUDE=100
% only use historical data that are within +/- yyy dbar from float data
MAP_P_DELTA=200`

**Comment by cabanesc** [comment]
Could it be the same problem as issue  #9 ?

Both  report a  similar error :
python/ow_calibration/tbase_decoder/tbase_decoder.py", line 70, in get_topo_grid
elev_file.seek((i + decoder [3]) * 360 * 12 * 2 + decoder [0] * 2)
OSError: [Errno 22] Invalid argument

**Comment by kamwal** [comment]
Thank Cecile, Yes it looks like the same issue for me.
