### ISSUE TITLE
Repository and package name

### ISSUE THREAD

**Issue by edsmall-bodc** [euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool#17]
Initially, the name of the repository was owc_python. However, this was changed because having the language name in the title of the repository is highly unusual.

It was suggested to go with argodmqc_owc, as it was thought that this gives the user a lot of information: It's an argo product used for delayed mode quaility control, and it continue to honour the original creators of Owens, Wong, and Cabanes.

However, it has been highlighted that leaving out the "python" part could cause some initial confusion between this version and the matlab version for users. It could be especially confusing during the time period where both code bases are in operation (before deprecating the matlab version).

@matdon17, @gmaze, @apswong, @cabanesc, and @kamwal, if you have any thoughts or opinions on this topic, please drop them here so that we can decide together.

**Comment by gmaze** [comment]
Using "py" in a python software is very usual, this could make the diff with the matlab software

**Comment by edsmall-bodc** [comment]
@gmaze Yeah, I like that. I remember owcpy or something being thrown around as a suggestion last time.

**Comment by gmaze** [comment]
I'm not sure in English, but ``owcpy`` in French is not easy to say ;-)

**Comment by edsmall-bodc** [comment]
Not easy to say in English either! We can try and come up with something snappy.

- pyowc (could be pronounced py - ock?)
- dmqcpy or dmqc_py
- salcorpy (salinity correction python package)

Do we feel we should keep the OWC name in there somewhere? To:

1. Honour the original creators
2. To ensure no current users get confused about what this python package is

**Comment by gmaze** [comment]
We should definitely keep the OWC name *around* there, this is the defining term for this software user community.
This means that we could have it in the tagline/definition that goes along the software nearly everywhere:

- [ ] "salcorpy: OWC salinity calibration for Argo"
- [ ] "pycalib: OWC salinity calibration for Argo"
- [ ] "argopy_calib: OWC salinity calibration"

I tend to prefer *calibration* over *correction*, but I'm not the expert about this.

**Comment by matdon17** [comment]
We already have a matlab_owc so the horse has bolted in terms of having a name in the title, and my main concern is clarity for users. when they land on its 'production' repo of https://github.com/ArgoDMQC

I am largely indifferent as to the exact name.  For instance I'd be happy with python_owc, owc_python, py_owc or owc_py.  I think trying to describe what it does in the name (as opposed to doing so in the description) is superfluous.

**Comment by gmaze** [comment]
> We already have a matlab_owc so the horse has bolted in terms of having a name in the title,

Agreed !

> I am largely indifferent as to the exact name.

Taking you to the word and looking for acronyms I had the amazing solution below [from acronymify](https://acronymify.com/search?q=argo+salinity+calibration+python)

**"ASCOT": Argo Salinity CalibratiOn in pyThon**

Would it be nice to have this elegant name (*a man's broad silk necktie* by the definition) and no difficulty to find a logo with it ?

I can't resist the *wink* to the developers country (Google Image gives me pages of UK Royal family pictures with ascot)

<img src="https://cdn0.iconfinder.com/data/icons/fathers-day-3-1/64/necktie_cravat_bowtie_ascot-512.png" data-canonical-src="https://cdn0.iconfinder.com/data/icons/fathers-day-3-1/64/necktie_cravat_bowtie_ascot-512.png" width="200" />

I hope this is not too cliché !

**Comment by apswong** [comment]
The Matlab version will not be deprecated.  Hence the Python repo should be named clearly so users do not get confused what this package is.  I would suggest:

"py_owc: OWC salinity calibration in Python"

This makes it very clear to the users that they have 2 choices: py_owc or matlab_owc.

**Comment by gmaze** [comment]
Is everybody happy with **pyowc** ?

Thumbs up or down please

We have to conclude on this because we gonna need a name for software packaging and distribution

**Comment by apswong** [comment]
py_owc please.
So it's similar to matlab_owc.

**Comment by gmaze** [comment]
ok, let's go for:
# py_owc

**Comment by gmaze** [comment]
One important thing to note, since we gonna have:

1. a name for the repository url: **argodmqc_owc** at this point. This name is to be considered only for developers, users won't have to see this one.

2. a name for the software distribution, ie the name people will use to search and install it, **py_owc** as defined above:
  ```bash
  pip install py_owc
  # conda install py_owc
  ```
3. a name for the library to be imported from a Python session: this is **ow_calibration** at this point:
```python
import ow_calibration
```

I think that having 3 names can be very confusing ! (although this is perfect to spot any errors in packaging)

**Comment by edsmall-bodc** [comment]
@gmaze I'm happy to rename the top level code to py_owc if it helps with clarity

**Comment by gmaze** [comment]
> @gmaze I'm happy to rename the top level code to py_owc if it helps with clarity

You mean to rename folder "ow_calibration" to "py_owc" ?

**Comment by gmaze** [comment]
I think it would be nice yes.
It's always confusing and frustrating to install "blabla" and to fail in importing "blabla" !

**Comment by edsmall-bodc** [comment]
I agree, it's nice when the `install <name>` is the same as the `import <name>`

**Comment by apswong** [comment]
Can the repo url: argodmqc_owc also be renamed to py_owc?

**Comment by gmaze** [comment]
> Can the repo url: argodmqc_owc also be renamed to py_owc?

yes, we can rename it, 
although this is less problematic than **py_owc** vs **ow_calibration** when we install/use it

**Comment by gmaze** [comment]
Please, now see: https://github.com/euroargodev/argodmqc_owc/issues/23#issuecomment-654273356
We basically can't use `py_owc` because it is changed to `py-owc` by the distribution platform.
I propose to simply work with **pyowc**, which still links to the Matlab counter part easily.

**Comment by gmaze** [comment]
thanks for your answers
So at some point the software and library will be named **pyowc**, we won't change the repo name (yet).

# pyowc
