### ISSUE TITLE
Trimmed size of variables in CAL_[WMO].m Python output

### ISSUE THREAD

**Issue by kamwal** [euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool#20]
I found that in the cal_[WMO].m Python output the size of four variables are smaller than those from Matlab version. These variables are: sta_mean, sta_rms, time_deriv and time_deriv_err.
In Matlab the size of these variables is 1x 215, where the last 37 values are NaN. In Python the size is 1x 178, and data includes only values not NaN. it looks like Python is tryming NaN values.
It would be good to check if the difference of size in Python output vs Matlab output will not affect any other calulations. 

WMO: 1901847
Reference data: CTD_for_DMQC_2019V01
WMO boxes: wmo_boxes_ctd.mat
Canfiguration:
`#    Objective Mapping Parameters
        #

        # max number of historical casts used in objective mapping
        'CONFIG_MAX_CASTS': 300,

        # 1=use PV constraint, 0=don't use PV constraint, in objective mapping
        'MAP_USE_PV': 0,

        # 1=use SAF separation criteria, 0=don't use SAF separation criteria, in objective mapping
        'MAP_USE_SAF': 0,

        # spatial decorrelation scales, in degrees
        'MAPSCALE_LONGITUDE_LARGE': 8,
        'MAPSCALE_LONGITUDE_SMALL': 4,
        'MAPSCALE_LATITUDE_LARGE': 4,
        'MAPSCALE_LATITUDE_SMALL': 2,

        # cross-isobath scales, dimensionless, see BS(2005)
        'MAPSCALE_PHI_LARGE': 0.1,
        'MAPSCALE_PHI_SMALL': 0.02,

        # temporal decorrelation scale, in years
        'MAPSCALE_AGE_LARGE': 20,
        'MAPSCALE_AGE_SMALL': 5,

        # exclude the top xxx dbar of the water column
        'MAP_P_EXCLUDE': 100,

        # only use historical data that are within +/- yyy dbar from float data
        'MAP_P_DELTA': 200
    }`

**Comment by matdon17** [comment]
Is this a candidate for preallocation of an array?

**Comment by kamwal** [comment]
The investigations showed that the smaller size of the matrix, is not affecting the calculations or the visualisation of data.
