### ISSUE TITLE
Default values in set_calseries.py

### ISSUE THREAD

**Issue by kamwal** [euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool#21]
In Python code the default values used in the set_calseries.py of _use theta_ and _pres_ are set as 0.  This value should be replaced by empty bracket [] to allow the system to automatically select the best theta levels. 

`breaks = []
        max_breaks = 4  # 0 for linear trend, -1 for offset
        calseries = np.ones((1, no_profiles)).flatten()
        # example for splitting time series at profile 33
        # calseries = np.concatenate((np.ones((1, 33)), 2 * np.ones(1,no_profiles - 33)))
        calib_profile_no = profile_no
        use_percent_gt = 0.5
        use_theta_lt = 0
        use_theta_gt = 0
        use_pres_lt = 0
        use_pres_gt = 0`

WMO: 1901847
Reference data: CTD_for_DMQC_2019V01
WMO boxes: wmo_boxes_ctd.mat
Canfiguration:
`# Objective Mapping Parameters
#

    # max number of historical casts used in objective mapping
    'CONFIG_MAX_CASTS': 300,

    # 1=use PV constraint, 0=don't use PV constraint, in objective mapping
    'MAP_USE_PV': 0,

    # 1=use SAF separation criteria, 0=don't use SAF separation criteria, in objective mapping
    'MAP_USE_SAF': 0,

    # spatial decorrelation scales, in degrees
    'MAPSCALE_LONGITUDE_LARGE': 8,
    'MAPSCALE_LONGITUDE_SMALL': 4,
    'MAPSCALE_LATITUDE_LARGE': 4,
    'MAPSCALE_LATITUDE_SMALL': 2,

    # cross-isobath scales, dimensionless, see BS(2005)
    'MAPSCALE_PHI_LARGE': 0.1,
    'MAPSCALE_PHI_SMALL': 0.02,

    # temporal decorrelation scale, in years
    'MAPSCALE_AGE_LARGE': 20,
    'MAPSCALE_AGE_SMALL': 5,

    # exclude the top xxx dbar of the water column
    'MAP_P_EXCLUDE': 100,

    # only use historical data that are within +/- yyy dbar from float data
    'MAP_P_DELTA': 200
}`

**Comment by edsmall-bodc** [comment]
Fixed in [#36](https://github.com/euroargodev/argodmqc_owc/pull/36)

**Comment by matdon17** [comment]
@kamwal @edsmall-bodc if this has been fixed in #36, can this issue be closed?
