### ISSUE TITLE
Large error and many NaN columns in error calculations in cal_<WMO>.mat

### ISSUE THREAD

**Issue by kamwal** [euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool#23]
In the Python output of cal_[WMO].mat, I have found  relatively large values in variables including error calulations: _cal_SAL_err_, _cal_COND_err_ and _ pcond_factor_err_ variable compared with those from Matlab outout. 

Moreover, in Python outout there are many columns with NaN that are not present in Matlab output. There are missing data in the begining and in the end part of the variable.

Top plot _cal_SAL_err_- Matlab output; Bottom plot _cal_SAL_err_py_- Python output; 

![image](https://user-images.githubusercontent.com/57108044/86233196-fc3ea180-bb8c-11ea-9453-d772de3ffea2.png)

Top plot _cal_COND_err_- Matlab output; Bottom plot _cal_COND_err_py_- Python output; 

![image](https://user-images.githubusercontent.com/57108044/86232740-4ecb8e00-bb8c-11ea-8670-5d93c356c9b8.png)

Top plot _pcond_factor_err_- Matlab output; Bottom plot _pcond_factor_err_py_- Python output; 

![image](https://user-images.githubusercontent.com/57108044/86231909-242d0580-bb8b-11ea-802e-da7d544c3cfb.png)

WMO: 1901847
Reference data: CTD_for_DMQC_2019V01
WMO boxes: wmo_boxes_ctd.mat
set_calseries:

` # Config calseries parameters

    breaks = []
    max_breaks = 4  # 0 for linear trend, -1 for offset
    calseries = np.ones((1, no_profiles)).flatten()
    # example for splitting time series at profile 33
    # calseries = np.concatenate((np.ones((1, 33)), 2 * np.ones(1,no_profiles - 33)))
    calib_profile_no = profile_no
    use_percent_gt = 0.5
    use_theta_lt = 0
    use_theta_gt = 0
    use_pres_lt = 0
    use_pres_gt = 0`

Canfiguration:
` # Objective Mapping Parameters
#

    # max number of historical casts used in objective mapping
    'CONFIG_MAX_CASTS': 300,

    # 1=use PV constraint, 0=don't use PV constraint, in objective mapping
    'MAP_USE_PV': 0,

    # 1=use SAF separation criteria, 0=don't use SAF separation criteria, in objective mapping
    'MAP_USE_SAF': 0,

    # spatial decorrelation scales, in degrees
    'MAPSCALE_LONGITUDE_LARGE': 8,
    'MAPSCALE_LONGITUDE_SMALL': 4,
    'MAPSCALE_LATITUDE_LARGE': 4,
    'MAPSCALE_LATITUDE_SMALL': 2,

    # cross-isobath scales, dimensionless, see BS(2005)
    'MAPSCALE_PHI_LARGE': 0.1,
    'MAPSCALE_PHI_SMALL': 0.02,

    # temporal decorrelation scale, in years
    'MAPSCALE_AGE_LARGE': 20,
    'MAPSCALE_AGE_SMALL': 5,

    # exclude the top xxx dbar of the water column
    'MAP_P_EXCLUDE': 100,

    # only use historical data that are within +/- yyy dbar from float data
    'MAP_P_DELTA': 200
}`

**Comment by edsmall-bodc** [comment]
This error is causing this issue:

![image](https://user-images.githubusercontent.com/55086028/89396115-12003300-d706-11ea-96d4-58d6d6e7e6e2.png)

**Comment by edsmall-bodc** [comment]
Much better: 

![image](https://user-images.githubusercontent.com/55086028/89407920-84c5da00-d717-11ea-8923-7f26a0e063b2.png)

- Error was caused by: using a deprecated function for finding the inverse of a matrix
- Taking square root of a mtrix incorrectly (eg doing dot(A - B)^2 instead of dot(A - B^2))

**Comment by kamwal** [comment]
The fixes used in https://github.com/euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool/issues/32 also decreased the error differences in error calulations: cal_SAL_err, cal_COND_err and _ pcond_factor_err_. Maximum differences between matlab and Python for error calulations are:

- cal_SAL_err: 0.002

- cal_COND_err: 0.0015

- pcond_factor_err: 3.8215e-05

Moreover, there is no more suspicious NaN columns in the matrix compared with Matlab output.

**Comment by kamwal** [comment]
The branch with the fix has been merged to the master branch
