### ISSUE TITLE
Setting exact brakepoints in set_calseries_py is not working

### ISSUE THREAD

**Issue by kamwal** [euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool#24]
I was trying to set an exact brakepoint in the float timeseries and I hit the following error:

`C:\Users\kamwal\Anaconda3\envs\Project_test\python.exe L:/users/argo/kamwal/OWC_Python_Test_2/argodmqc_owc/owc_calibration.py
Traceback (most recent call last):
  File "C:\Users\kamwal\Anaconda3\envs\Project_test\lib\site-packages\scipy\io\matlab\mio.py", line 39, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: 'data/float_calib//calseries_1901847.mat'
`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\set_calseries\set_calseries.py", line 55, in set_calseries
    calseries_data = scipy.loadmat(calseries_filename)
  File "C:\Users\kamwal\Anaconda3\envs\Project_test\lib\site-packages\scipy\io\matlab\mio.py", line 216, in loadmat
    with _open_file_context(file_name, appendmat) as f:
  File "C:\Users\kamwal\Anaconda3\envs\Project_test\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "C:\Users\kamwal\Anaconda3\envs\Project_test\lib\site-packages\scipy\io\matlab\mio.py", line 19, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
  File "C:\Users\kamwal\Anaconda3\envs\Project_test\lib\site-packages\scipy\io\matlab\mio.py", line 45, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: 'data/float_calib//calseries_1901847.mat'`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "L:/users/argo/kamwal/OWC_Python_Test_2/argodmqc_owc/owc_calibration.py", line 79, in <module>
    set_calseries("/", FLOAT_NAME, USER_CONFIG)
  File "L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\set_calseries\set_calseries.py", line 83, in set_calseries
    calseries = np.concatenate((np.ones((1, 40)), 2 * np.ones(1,no_profiles - 40)))
  File "C:\Users\kamwal\Anaconda3\envs\Project_test\lib\site-packages\numpy\core\numeric.py", line 207, in ones
    a = empty(shape, dtype, order)
TypeError: data type not understood`

`Process finished with exit code 1`

WMO: 1901847
Reference data: CTD_for_DMQC_2019V01
WMO boxes: wmo_boxes_ctd.mat
set_calseries:

`breaks = []
        max_breaks = 4  # 0 for linear trend, -1 for offset
        #calseries = np.ones((1, no_profiles)).flatten()
        # example for splitting time series at profile 33
        calseries = np.concatenate((np.ones((1, 40)), 2 * np.ones(1,no_profiles - 40)))
        calib_profile_no = profile_no
        use_percent_gt = 0.5
        use_theta_lt = 0
        use_theta_gt = 0
        use_pres_lt = 0
        use_pres_gt = 0`

Canfiguration:
`        #    Objective Mapping Parameters
        #

        # max number of historical casts used in objective mapping
        'CONFIG_MAX_CASTS': 300,

        # 1=use PV constraint, 0=don't use PV constraint, in objective mapping
        'MAP_USE_PV': 0,

        # 1=use SAF separation criteria, 0=don't use SAF separation criteria, in objective mapping
        'MAP_USE_SAF': 0,

        # spatial decorrelation scales, in degrees
        'MAPSCALE_LONGITUDE_LARGE': 8,
        'MAPSCALE_LONGITUDE_SMALL': 4,
        'MAPSCALE_LATITUDE_LARGE': 4,
        'MAPSCALE_LATITUDE_SMALL': 2,

        # cross-isobath scales, dimensionless, see BS(2005)
        'MAPSCALE_PHI_LARGE': 0.1,
        'MAPSCALE_PHI_SMALL': 0.02,

        # temporal decorrelation scale, in years
        'MAPSCALE_AGE_LARGE': 20,
        'MAPSCALE_AGE_SMALL': 5,

        # exclude the top xxx dbar of the water column
        'MAP_P_EXCLUDE': 100,

        # only use historical data that are within +/- yyy dbar from float data
        'MAP_P_DELTA': 200`

**Comment by edsmall-bodc** [comment]
@kamwal Apologies, it's just missing a set of brackets when concatenating the matrices together in set_calseries.

However, this has popped up another instance in fit_cond where we want to use indices but they are stored as a float, rather than as an integer. Will sort out for you this evening so you can test this part of the calibration tomorrow.

**Comment by edsmall-bodc** [comment]
Also, we don't need the objective mapping parameters for errors in the calibration - they are only relevant for the salinity mapping.

Instead, what you should log is your calseries parameters (usually line 75 to 92 in set_calseries) 

Example:

`    except FileNotFoundError:

        # Config calseries parameters

        breaks = []
        max_breaks = 4  # 0 for linear trend, -1 for offset
        calseries = np.ones((1, no_profiles)).flatten()
        # example for splitting time series at profile 33
        a = np.ones((1, 33)).flatten()
        b = 2 * np.ones((1, no_profiles - 33)).flatten()
        calseries = np.concatenate((a, b))
        calib_profile_no = profile_no
        use_percent_gt = 0.5
        use_theta_lt = 0
        use_theta_gt = 0
        use_pres_lt = 0
        use_pres_gt = 0`
