### ISSUE TITLE
Error in setting max_brake in set_calseries.py for values below 4 

### ISSUE THREAD

**Issue by kamwal** [euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool#25]
I cant set the _max_brake_ values smaller than 4 in the set_calseries.py

Error for max_brake : -1

`C:\Users\kamwal\Anaconda3\envs\Project_test\python.exe L:/users/argo/kamwal/OWC_Python_Test_2/argodmqc_owc/owc_calibration.py
L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\find_10thetas\find_10thetas.py:175: RuntimeWarning: invalid value encountered in greater
  if np.nanmax(ptmp[:, depth]) > theta_levels[level] > np.nanmin(ptmp[:, depth]):
L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\find_10thetas\find_10thetas.py:203: RuntimeWarning: invalid value encountered in greater
  pos_diff = np.argwhere(ptmp_diff > 0)
L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\find_10thetas\find_10thetas.py:213: RuntimeWarning: invalid value encountered in less
  neg_diff = np.argwhere(ptmp_diff < 0)
L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\find_10thetas\find_10thetas.py:252: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var_sal_tlevels[i] = np.nanvar(sal_temp[i, good], ddof=1)
Traceback (most recent call last):
  File "L:/users/argo/kamwal/OWC_Python_Test_2/argodmqc_owc/owc_calibration.py", line 82, in <module>
    calc_piecewisefit("/", FLOAT_NAME, USER_CONFIG)
  File "L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\calc_piecewisefit\calc_piecewisefit.py", line 283, in calc_piecewisefit
    sta_mean, sta_rms, ndf, fit_coef, fit_breaks) = fit_cond(x, y, err,
  File "L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\fit_cond\fit_cond.py", line 317, in fit_cond
    b_pts = np.ones((max_brk_in, max_brk_in + 1)) * np.nan
  File "C:\Users\kamwal\Anaconda3\envs\Project_test\lib\site-packages\numpy\core\numeric.py", line 207, in ones
    a = empty(shape, dtype, order)
ValueError: negative dimensions are not allowed`

`Process finished with exit code 1`

Error for max_brake : 0

`C:\Users\kamwal\Anaconda3\envs\Project_test\python.exe L:/users/argo/kamwal/OWC_Python_Test_2/argodmqc_owc/owc_calibration.py
L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\find_10thetas\find_10thetas.py:175: RuntimeWarning: invalid value encountered in greater
  if np.nanmax(ptmp[:, depth]) > theta_levels[level] > np.nanmin(ptmp[:, depth]):
L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\find_10thetas\find_10thetas.py:203: RuntimeWarning: invalid value encountered in greater
  pos_diff = np.argwhere(ptmp_diff > 0)
L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\find_10thetas\find_10thetas.py:213: RuntimeWarning: invalid value encountered in less
  neg_diff = np.argwhere(ptmp_diff < 0)
L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\find_10thetas\find_10thetas.py:252: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var_sal_tlevels[i] = np.nanvar(sal_temp[i, good], ddof=1)
Traceback (most recent call last):
  File "L:/users/argo/kamwal/OWC_Python_Test_2/argodmqc_owc/owc_calibration.py", line 82, in <module>
    calc_piecewisefit("/", FLOAT_NAME, USER_CONFIG)
  File "L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\calc_piecewisefit\calc_piecewisefit.py", line 283, in calc_piecewisefit
    sta_mean, sta_rms, ndf, fit_coef, fit_breaks) = fit_cond(x, y, err,
  File "L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\fit_cond\fit_cond.py", line 391, in fit_cond
    b_A[0:2, 1] = A[0:2]
IndexError: index 1 is out of bounds for axis 1 with size 1`

`Process finished with exit code 1`

Error for max_brake : 1

`C:\Users\kamwal\Anaconda3\envs\Project_test\python.exe L:/users/argo/kamwal/OWC_Python_Test_2/argodmqc_owc/owc_calibration.py
L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\find_10thetas\find_10thetas.py:175: RuntimeWarning: invalid value encountered in greater
  if np.nanmax(ptmp[:, depth]) > theta_levels[level] > np.nanmin(ptmp[:, depth]):
L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\find_10thetas\find_10thetas.py:203: RuntimeWarning: invalid value encountered in greater
  pos_diff = np.argwhere(ptmp_diff > 0)
L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\find_10thetas\find_10thetas.py:213: RuntimeWarning: invalid value encountered in less
  neg_diff = np.argwhere(ptmp_diff < 0)
L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\find_10thetas\find_10thetas.py:252: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var_sal_tlevels[i] = np.nanvar(sal_temp[i, good], ddof=1)
Traceback (most recent call last):
  File "L:/users/argo/kamwal/OWC_Python_Test_2/argodmqc_owc/owc_calibration.py", line 82, in <module>
    calc_piecewisefit("/", FLOAT_NAME, USER_CONFIG)
  File "L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\calc_piecewisefit\calc_piecewisefit.py", line 283, in calc_piecewisefit
    sta_mean, sta_rms, ndf, fit_coef, fit_breaks) = fit_cond(x, y, err,
  File "L:\users\argo\kamwal\OWC_Python_Test_2\argodmqc_owc\ow_calibration\fit_cond\fit_cond.py", line 438, in fit_cond
    b_A[0:nbr + 2, nbr + 1] = A[0:nbr + 2]
IndexError: index 2 is out of bounds for axis 1 with size 2`

`Process finished with exit code 1
`

WMO: 1901847
Reference data: CTD_for_DMQC_2019V01
WMO boxes: wmo_boxes_ctd.mat
Canfiguration:
`        #    Objective Mapping Parameters
        #

        # max number of historical casts used in objective mapping
        'CONFIG_MAX_CASTS': 300,

        # 1=use PV constraint, 0=don't use PV constraint, in objective mapping
        'MAP_USE_PV': 0,

        # 1=use SAF separation criteria, 0=don't use SAF separation criteria, in objective mapping
        'MAP_USE_SAF': 0,

        # spatial decorrelation scales, in degrees
        'MAPSCALE_LONGITUDE_LARGE': 8,
        'MAPSCALE_LONGITUDE_SMALL': 4,
        'MAPSCALE_LATITUDE_LARGE': 4,
        'MAPSCALE_LATITUDE_SMALL': 2,

        # cross-isobath scales, dimensionless, see BS(2005)
        'MAPSCALE_PHI_LARGE': 0.1,
        'MAPSCALE_PHI_SMALL': 0.02,

        # temporal decorrelation scale, in years
        'MAPSCALE_AGE_LARGE': 20,
        'MAPSCALE_AGE_SMALL': 5,

        # exclude the top xxx dbar of the water column
        'MAP_P_EXCLUDE': 100,

        # only use historical data that are within +/- yyy dbar from float data
        'MAP_P_DELTA': 200
    }`

**Comment by edsmall-bodc** [comment]
Also might be fixed via https://github.com/euroargodev/argodmqc_owc/pull/40

**Comment by kamwal** [comment]
After consultation with @edsmall-bodc I have tested the configuration.py for max_break from 0 to 4. After testing a few floats I have found a strange behaviour when for some floats I can use max_break from 0 to 3 and for others not. 

In detailed check, I have found that the max_break setting is working if the max_break in configuration.py script is set to be larger than those automatically estimated by software during code iteration "The maximum breakpoints to be tried" by software.  

For instance, for float 3901985, in configuration.py, I set to max_breaks from 1 to 4. 

![image](https://user-images.githubusercontent.com/57108044/88552129-9e7e6780-d01b-11ea-9057-3d5fab342099.png)

Then, when I run the code, there was the message that "The maximum breakpoints to be tried: 0.0 " . 
With this set, the code is working well.

![image](https://user-images.githubusercontent.com/57108044/88552236-c40b7100-d01b-11ea-9757-2b0bffa862fc.png)

However when in set in configuration.py value equal or smaller than those automatically estimated by software to be e.g 0 or -1 the code is not working.

![image](https://user-images.githubusercontent.com/57108044/88552801-6af00d00-d01c-11ea-9cd0-fa707ab84a03.png)


I have tested this pattern for some other floats and I find the same strange issue: 

3901531- In the configuration.py I set max_break as 0. 
The max break automatically selected by the software is "The maximum breakpoints to be tried: -1 ". With this sets, code is working well. However, when I set the max_break to equal be -1, the code is crashing.

6901121-  In the configuration.py I set max_break as 3.
The the max break automatically selected by the software is "The maximum breakpoints to be tried: 2 ". In this case,
code is only working for max_breaks set from 3 and above. Code is crashing when I select max_break 2 and below.

1901847- not working for any max breaks, even 4. This is not working due to different issue::
 https://github.com/euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool/issues/32

**Comment by edsmall-bodc** [comment]
Can you attach the floats source, mapped salinities, and calseries files please? Need to check these outputs

**Comment by kamwal** [comment]
I am including data you asked for. All of data has been set to max brake 4.
[data.zip](https://github.com/euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool/files/5000730/data.zip)

**Comment by edsmall-bodc** [comment]
I think I have fixed this.

This bug technically exists in matlab too, but because of the way matlab handles matrices it doesn't pop up

The variable b_A in fit_cond is set up in such a way that if the maximum number of breaks set by the user is lower than the number of breaks that the software would have calculated, b_A has too few columns to fit in values.

Matlab creates new columns out of thin air, but python won't unless you specifically ask it to.

**Comment by kamwal** [comment]
I can confirm that issue with setting max_breaks has been fixed
