### ISSUE TITLE
Error in fit_cond ?

### ISSUE THREAD

**Issue by cabanesc** [euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool#26]
Hi,
I get this error when running the code for the float 6902766.

[6902766.mat.gz](https://github.com/euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool/files/4871226/6902766.mat.gz)
[map_6902766.mat.gz](https://github.com/euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool/files/4871227/map_6902766.mat.gz)

Traceback (most recent call last):
  File "owc_calibration.py", line 81, in <module>
    calc_piecewisefit("/", FLOAT_NAME, USER_CONFIG)
  File "/home1/homedir5/perso/ccabanes/dvlpRD/Argo/UAT/argodmqc_owc/ow_calibration/calc_piecewisefit/calc_piecewisefit.py", line 286, in calc_piecewisefit
    max_breaks[i][0])
  File "/home1/homedir5/perso/ccabanes/dvlpRD/Argo/UAT/argodmqc_owc/ow_calibration/fit_cond/fit_cond.py", line 373, in fit_cond
    if nbr == -1:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Values in set_calseries are the default ones.

The configuration file is: 
        # ===============================
        #
        #    Constants File Path
        #

        'CONFIG_DIRECTORY': "data/constants/",
        'CONFIG_COASTLINES': "coastdat.mat",
        'CONFIG_WMO_BOXES': "wmo_boxes_ctd.mat",
        'CONFIG_SAF': "TypicalProfileAroundSAF.mat",

        # ===============================
        #
        #    Objective Mapping Parameters
        #

        # max number of historical casts used in objective mapping
        'CONFIG_MAX_CASTS': 250,

        # 1=use PV constraint, 0=don't use PV constraint, in objective mapping
        'MAP_USE_PV': 0,

        # 1=use SAF separation criteria, 0=don't use SAF separation criteria, in objective mapping
        'MAP_USE_SAF': 0,

        # spatial decorrelation scales, in degrees
        'MAPSCALE_LONGITUDE_LARGE': 3.2,
        'MAPSCALE_LONGITUDE_SMALL': 2,
        'MAPSCALE_LATITUDE_LARGE': 2,
        'MAPSCALE_LATITUDE_SMALL': 1,

        # cross-isobath scales, dimensionless, see BS(2005)
        'MAPSCALE_PHI_LARGE': 0.1,
        'MAPSCALE_PHI_SMALL': 0.01,

        # temporal decorrelation scale, in years
        'MAPSCALE_AGE_LARGE': 2,
        'MAPSCALE_AGE_SMALL': 0.69,

        # exclude the top xxx dbar of the water column
        'MAP_P_EXCLUDE': 200,

        # only use historical data that are within +/- yyy dbar from float data
        'MAP_P_DELTA': 250
    }

**Comment by edsmall-bodc** [comment]
Do you mind posting your calseries parameters here too? The config parameters don't have too much to do with the piecewise fit stuff! Thanks

**Comment by edsmall-bodc** [comment]
Looks like nbr is set as an array/list here, not a number, so it's not happy doing the comparison.

I'll have a look at the matlab version and report back.

**Comment by cabanesc** [comment]
The config parameters are needed in fit_cond to compute the covariance matrix (build_cov)
The calseries parameters are the default ones.

**Comment by edsmall-bodc** [comment]
Ah, of course! Thank you

**Comment by kamwal** [comment]
After corrections applied by @edsmall-bodc this issue has been fixed.
