### ISSUE TITLE
Add automatic option to display and save all diagnostic plots

### ISSUE THREAD

**Issue by kamwal** [euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool#27]
Currently, the Python code is only displaying plots without  saving them to the  data/floats_plots directory.
The plots need to be save manually via the plot window. 
It would be worth to add the automatic option to save all plots in one go. 
I think that the most recommended format still can stay as pdf/.eps. 

Worth to note, that to display another diagnostic plot I need to close the previous plot. Again, it would be good to let the code display all off the plots on the screen.

**Comment by matdon17** [comment]
Investigation confirms that current version of OWC Matlab saves as EPS file be default.  Presumably we want the same behaviour.

It has been suggested this could be a new configuration setting to give people the option, rather than making any changes in the code.

**Comment by apswong** [comment]
An option to save the figures in png might be a nice thing to do.

**Comment by edsmall-bodc** [comment]
Should be fixed in https://github.com/euroargodev/argodmqc_owc/pull/41

The user can set a parameter in the config file to choose their file format. Default is eps.
