### ISSUE TITLE
Legend range in T/S plot of uncalibrated and calibrated  float data

### ISSUE THREAD

**Issue by kamwal** [euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool#28]
In Python version of T/S plot of uncalibrated and calibrated float data, the legend is displying only elements for six profiles, from the range between 0 and 25 profiles. The legend should represent the profiles from the entire length of the float life, e.g. every 5th profile.

After consultation with Ed, the code should display in legend max 30 elements. At the moment, code is displying elements taken only from the first 30 profiles, which is a bug.

Python plot at the left and Matlab plot at the right

![image](https://user-images.githubusercontent.com/57108044/86581211-b8c2a980-bf77-11ea-9032-4c0f74592455.png)

Reference data: CTD_for_DMQC_2019V01
WMO boxes: wmo_boxes_ctd.mat
Cal series:
       ` breaks = []
        max_breaks = 4  # 0 for linear trend, -1 for offset
        calseries = np.ones((1, no_profiles)).flatten()
        # example for splitting time series at profile 33
        # calseries = np.concatenate((np.ones((1, 33)), 2 * np.ones(1,no_profiles - 33)))
        calib_profile_no = profile_no
        use_percent_gt = 0.5
        use_theta_lt =0
        use_theta_gt =0
        use_pres_lt =0
        use_pres_gt = 0`

**Comment by kamwal** [comment]
The minor note is that both uncalibrated and calibrated plots from Python code do not have float number in the plot title.

**Comment by edsmall-bodc** [comment]
This will be fixed in [THIS PR](https://github.com/euroargodev/argodmqc_owc/pull/22)

**Comment by matdon17** [comment]
Can this issue be closed now?
