### ISSUE TITLE
Missing separation line in Plot of vertical averaged salinity 

### ISSUE THREAD

**Issue by kamwal** [euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool#29]
I found that plot with the vertically averaged salinity does not include the zero line. I think that for operators it is very usefull line to quickly check the float behaviour whether float shows negaitve or positie anomalies. 

There is also no separation line  at 1, in the plot of the potential conductivity miltiplicative correction.

Left -Python plot; Right -Matlab plot
![image](https://user-images.githubusercontent.com/57108044/86583608-78652a80-bf7b-11ea-9cd9-8e8bdd15acdb.png)

Reference data: CTD_for_DMQC_2019V01
WMO boxes: wmo_boxes_ctd.mat
Cal series:
breaks = [] max_breaks = 4 # 0 for linear trend, -1 for offset calseries = np.ones((1, no_profiles)).flatten() # example for splitting time series at profile 33 # calseries = np.concatenate((np.ones((1, 33)), 2 * np.ones(1,no_profiles - 33))) calib_profile_no = profile_no use_percent_gt = 0.5 use_theta_lt =0 use_theta_gt =0 use_pres_lt =0 use_pres_gt = 0

**Comment by edsmall-bodc** [comment]
Okay, Easy enough to add. It is always at 1 in the first plot, 0 in the second?

**Comment by kamwal** [comment]
Yes!

**Comment by edsmall-bodc** [comment]
Fixed in https://github.com/euroargodev/argodmqc_owc/pull/44
