### ISSUE TITLE
Missing plot - Salinity anom on theta

### ISSUE THREAD

**Issue by kamwal** [euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool#31]
The the master code of OWC code there is missing of one diagnostic plot of the time series of salinity data plotted on theta levels, for both uncalibrated and calibrated data. 

The Python version of this plot is created and ready to use, however Ed had accidently forgot to move it to master branch.

Matlab version of this plot

![image](https://user-images.githubusercontent.com/57108044/86600285-c556fa00-bf97-11ea-9078-bf61c037441d.png)

**Comment by edsmall-bodc** [comment]
Can I ask, when it says "salinity anomaly" what is it actually referring to? How different the original float profile is to the calibrated version? Or how different the original is to the mapped salinity? Etc.

**Comment by edsmall-bodc** [comment]
If I remember correctly, this plot shows up twice. Is one the difference between float salinity and mapped salinity, and the other the difference between calibrated salinity and mapped salinity?

**Comment by apswong** [comment]
Hello, "salinity anomaly" in this routine is simply float salinity minus the median value of float salinity:
FLOATSALINITY_anomaly = FLOATSALINITY - FLOATSALINITY_median

It is similar to looking at descriptive statistic terms such as standard deviation, which helps to highlight values that are far from the median.

The plot is done twice: (a) uses the raw float salinity with no adjustment; (b) uses the calibrated salinity from OWC computation.

So, for example, if a float is drifting salty, then (a) will show the raw salinity deviation from median becoming greater with time, so the plot will show more "red" with time; (b) will, hopefully, show OWC calibration able to pull the values back to normal, and so the plot will show neutral color through time.

**Comment by edsmall-bodc** [comment]
Hi Annie, glad I was on the right lines! I want to remake some of the code and then pull it in - there's a lot of faff in there that this routine does not need that  I've written.

**Comment by kamwal** [comment]
The missing plot now has been added to the code. I think it is very nice.
Left- Python code, Right- Matlab code

![image](https://user-images.githubusercontent.com/57108044/91986613-d23c6380-ed24-11ea-8a3a-91526a36228c.png)

**Comment by Teddyzander** [comment]
y axis scales are selected in the configuration set up. There's a new section of parameters called "Plot Parameters". This is so that people don't need to dig around in the actual code to change plots. We can add more parameters here, if we wish. It also means that the configuration for plots can be changed dynamically between different analysis.

**Comment by edsmall-bodc** [comment]
Sorry, the above is my personal account!

**Comment by kamwal** [comment]
The plot was added to the master branch
