### ISSUE TITLE
Disagreement in plots of salinities at specific theta levels

### ISSUE THREAD

**Issue by kamwal** [euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool#34]
I found that the Python plot of salinities at specific theta levels is giving much different result copared with Matlab version. Plots from Python show much more spikes in both climatology and float data. 

[6901121.zip](https://github.com/euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool/files/4885392/6901121.zip)

Plot from Matlab
![image](https://user-images.githubusercontent.com/57108044/86782918-91dba480-c057-11ea-817f-aa2acdc86b1e.png)

Plot from Python
![image](https://user-images.githubusercontent.com/57108044/86783041-ba639e80-c057-11ea-82f0-ad52dc551a6d.png)
![image](https://user-images.githubusercontent.com/57108044/86796846-e8041400-c066-11ea-88ed-958b5bdeb766.png)
![image](https://user-images.githubusercontent.com/57108044/86797338-75dfff00-c067-11ea-8dbb-c6dc094d92fc.png)

WMO: 6901121
Reference data: CTD_for_DMQC_2019V01
WMO boxes: wmo_boxes_ctd.mat
Cal series:
`breaks = [] max_breaks = 4 # 0 for linear trend, -1 for offset calseries = np.ones((1, no_profiles)).flatten() # example for splitting time series at profile 33 # calseries = np.concatenate((np.ones((1, 33)), 2 * np.ones(1,no_profiles - 33))) calib_profile_no = profile_no use_percent_gt = 0.5 use_theta_lt =0 use_theta_gt =0 use_pres_lt =0 use_pres_gt = 0`

**Comment by edsmall-bodc** [comment]
I'm going to first try adjusting the axis and presentation to make sure that it is definitely wrong. It could be that something is skewing the image a little.

I'll post them here, and then we can have a look again. Can you email me the mapped salinity, float source, and calibrated salinity?

**Comment by kamwal** [comment]
I didnt find that kind of issue in any other float that I am testing.

**Comment by kamwal** [comment]
Another example where there can be spotted some minor disagreement in plots 
WMO: 5900178

Data to this float : [5900178.zip](https://github.com/euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool/files/4891081/5900178.zip)

Upper plot- Python; Lower plot- Matlab
![image](https://user-images.githubusercontent.com/57108044/86926350-d9cafc00-c129-11ea-8391-e67dbe133656.png)

**Comment by edsmall-bodc** [comment]
Definitely something weird going on here. Attach your mapped salinity, calibrated salinity, and calseries file here in a zip, if you can, for the above float

**Comment by kamwal** [comment]
[5900178.zip](https://github.com/euroargodev/User-Acceptance-Test-Python-version-of-the-OWC-tool/files/4891081/5900178.zip)

**Comment by kamwal** [comment]
After discussion with @edsmall-bodc the fix of this issue should be done by correcting another issue with the global variables.
I have checked all 10 theta levels from matlab and python outputs, respectively. Both Matlab and Python code is selecting the same theta levels, however the displayed data by both software still disagreed. 
More investigations in this issue is still required.

**Comment by kamwal** [comment]
The issue with the disagreement of plots plotted at the same theta levels has been identified.
The branch with the fix is available in branch: 
https://github.com/euroargodev/argodmqc_owc/tree/kamwal/disagre_theta

Plots from Python:
![image](https://user-images.githubusercontent.com/57108044/105048022-fb0a8e80-5a62-11eb-9d35-4ececc620f8b.png)
![image](https://user-images.githubusercontent.com/57108044/105048155-22f9f200-5a63-11eb-8e92-e36794a84c8d.png)

**Comment by kamwal** [comment]
In testing the code using example  WMO 5900178 the plots from both matlab and Python looks very similar now
Upper plot - Python, Lower plot - Matlab

![image](https://user-images.githubusercontent.com/57108044/105051758-fcd65100-5a66-11eb-9d7b-c4a8b1a5bead.png)

**Comment by kamwal** [comment]
The issue has been solved and merged to master branch [git merge ](https://github.com/euroargodev/argodmqc_owc/pull/50)
